=== BJCode-git/SuperMarioWorld/assets/levels/levelSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- http://www.w3schools.com/schema/schema_example.asp -->

	<!-- Generic definition for sprite elements -->
	<xs:complexType name="sprite_type">
		<xs:attribute name="x" type="xs:nonNegativeInteger"/>
		<xs:attribute name="y" type="xs:nonNegativeInteger"/>
		<xs:attribute name="sprite" type="xs:string"/>
	</xs:complexType>

	<!-- Definition of base elements -->
	<xs:element name="mario">
		<xs:complexType>
			<xs:attribute name="x" type="xs:nonNegativeInteger"/>
			<xs:attribute name="y" type="xs:nonNegativeInteger"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="goomba">
		<xs:complexType>
			<xs:attribute name="x" type="xs:nonNegativeInteger"/>
			<xs:attribute name="y" type="xs:nonNegativeInteger"/>
			<xs:attribute name="direction" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="box" type="sprite_type"/>

	<xs:element name="pipe">
		<xs:complexType>
			<xs:attribute name="x" type="xs:nonNegativeInteger"/>
			<xs:attribute name="y" type="xs:nonNegativeInteger"/>
			<xs:attribute name="sprite" type="xs:string"/>
			<xs:attribute name="type" type="xs:string"/>
			<xs:attribute name="id" type="xs:positiveInteger"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="floor_tile" type="sprite_type"/>

	<!-- Definition of complex elements -->
	<xs:element name="level">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="characters">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="mario" minOccurs="1" maxOccurs="1"/>
							<xs:element ref="goomba" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="foreground">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="pipe" minOccurs="0" maxOccurs="1"/>
							<xs:element ref="box" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element ref="floor_tile" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			
			<xs:attribute name="height" type="xs:positiveInteger"/>
			<xs:attribute name="width" type="xs:positiveInteger"/>
			<xs:attribute name="background" type="xs:string"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BJCode-git/SuperMarioWorld/assets/levels/activelvl.xml
<?xml version="1.0" encoding="UTF-8"?>
<level height="464" width="1024" background="sky" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="levelSchema.xsd">
	<characters>
		<mario x="80" y="428"/>
	</characters>
	<foreground>
		<pipe x="480" y="384" sprite="green_pipe_h" type="spawn" id="1"/>

		<box x="40" y="384" sprite="question_box_static"/>
		<box x="264" y="384" sprite="question_box_static"/>
		<box x="344" y="384" sprite="question_box_static"/>
		<box x="424" y="384" sprite="question_box_static"/>

		<box x="344" y="320" sprite="question_box"/>

		<floor_tile x="0" y="448" sprite="left"/>
		<floor_tile x="16" y="448" sprite="middle"/>
		<floor_tile x="32" y="448" sprite="middle"/>
		<floor_tile x="48" y="448" sprite="middle"/>
		<floor_tile x="64" y="448" sprite="middle"/>
		<floor_tile x="80" y="448" sprite="middle"/>
		<floor_tile x="96" y="448" sprite="middle"/>
		<floor_tile x="112" y="448" sprite="middle"/>
		<floor_tile x="128" y="448" sprite="right"/>
		<floor_tile x="208" y="448" sprite="left"/>
		<floor_tile x="224" y="448" sprite="middle"/>
		<floor_tile x="240" y="448" sprite="middle"/>
		<floor_tile x="256" y="448" sprite="middle"/>
		<floor_tile x="272" y="448" sprite="middle"/>
		<floor_tile x="288" y="448" sprite="middle"/>
		<floor_tile x="304" y="448" sprite="middle"/>
		<floor_tile x="320" y="448" sprite="middle"/>
		<floor_tile x="336" y="448" sprite="middle"/>
		<floor_tile x="352" y="448" sprite="middle"/>
		<floor_tile x="368" y="448" sprite="middle"/>
		<floor_tile x="384" y="448" sprite="middle"/>
		<floor_tile x="400" y="448" sprite="middle"/>
		<floor_tile x="416" y="448" sprite="middle"/>
		<floor_tile x="432" y="448" sprite="middle"/>
		<floor_tile x="448" y="432" sprite="middle"/>
		<floor_tile x="464" y="416" sprite="middle"/>
		<floor_tile x="480" y="448" sprite="left"/>
		<floor_tile x="496" y="448" sprite="middle"/>
		<floor_tile x="512" y="448" sprite="middle"/>
		<floor_tile x="528" y="448" sprite="middle"/>
		<floor_tile x="544" y="448" sprite="middle"/>
		<floor_tile x="560" y="448" sprite="middle"/>
		<floor_tile x="576 " y="448" sprite="middle"/>
		<floor_tile x="592 " y="448" sprite="middle"/>
		<floor_tile x="608 " y="448" sprite="middle"/>
		<floor_tile x="624 " y="448" sprite="middle"/>
		<floor_tile x="640 " y="448" sprite="middle"/>
		<floor_tile x="656 " y="448" sprite="middle"/>
		<floor_tile x="672 " y="448" sprite="middle"/>
		<floor_tile x="688 " y="448" sprite="middle"/>
		<floor_tile x="704 " y="448" sprite="middle"/>
		<floor_tile x="720 " y="448" sprite="middle"/>
		<floor_tile x="736 " y="448" sprite="middle"/>
		<floor_tile x="752 " y="448" sprite="middle"/>
		<floor_tile x="768 " y="448" sprite="middle"/>
		<floor_tile x="784 " y="448" sprite="middle"/>
		<floor_tile x="800 " y="448" sprite="middle"/>
		<floor_tile x="816 " y="448" sprite="middle"/>
		<floor_tile x="832 " y="448" sprite="middle"/>
		<floor_tile x="848 " y="448" sprite="middle"/>
		<floor_tile x="864 " y="448" sprite="middle"/>
		<floor_tile x="880 " y="448" sprite="middle"/>
		<floor_tile x="896 " y="448" sprite="middle"/>
		<floor_tile x="912 " y="448" sprite="middle"/>
		<floor_tile x="928 " y="448" sprite="middle"/>
		<floor_tile x="944 " y="448" sprite="middle"/>
		<floor_tile x="960 " y="448" sprite="middle"/>
		<floor_tile x="976 " y="448" sprite="middle"/>
		<floor_tile x="992 " y="448" sprite="middle"/>
		<floor_tile x="1008" y="448" sprite="right"/>
	</foreground>
</level>
